######################################################################
#
# File name : sim_tb_top_simulate.do
# Created on: Mon Jan 01 21:23:35 CST 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.sim_tb_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {sim_tb_top_wave.do}

view wave
view structure
view signals

do {sim_tb_top.udo}

run 1000ns

source {../../../../imports/xsim_options.tcl}

