######################################################################
#
# File name : sim_tb_top_wave.do
# Created on: Sun Dec 31 23:54:09 CST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
