#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Mentor Graphics ModelSim Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jan 01 21:23:35 CST 2024
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
bin_path="/home/fpga/software/modelsim/modeltech/bin"
set -Eeuo pipefail
$bin_path/vsim -64  -do "do {sim_tb_top_simulate.do}" -l simulate.log

