################################################################################
# File name: vivado_wc_pre.tcl
# Purpose  : This is an internal file that is auto generated by Vivado to source
#            the user tcl file.
################################################################################
open_project "/home/fpga/u1_library/k2_smart_eye/smart_eye_upl_demo2/uart.xpr"
set rc [catch {
  source -notrace "/home/fpga/u1_library/k2_smart_eye/smart_eye_upl_demo2/uart.srcs/utils_1/sim_pre.tcl"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: Script failed:\"/home/fpga/u1_library/k2_smart_eye/smart_eye_upl_demo2/uart.srcs/utils_1/sim_pre.tcl\""
}
close_project
